server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/japanbhatt/app-config.git

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG
